name: never_stop_scrolling
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_bloc: ^9.0.0
  flutter_svg: ^2.0.17
  hive: ^2.2.3
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/other/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-UltraLight.otf
          weight: 100
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 200
        - asset: assets/fonts/Gilroy-Thin.otf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.otf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.otf
          weight: 600
        - asset: assets/fonts/Gilroy-SemiBold.otf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Gilroy-Heavy.otf
          weight: 900
        - asset: assets/fonts/Gilroy-Black.otf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.jpg
